// ═══════════════════════════════════════════════════════════════════════
// NEON ARCADE — Status Reporter
// ═══════════════════════════════════════════════════════════════════════

import type { AgentId } from '../schemas/schemas';
import { AGENT_ROSTER } from '../agents/agent-definitions';

/**
 * Generates markdown status reports for each agent after task completion.
 */
export class StatusReporter {

  /**
   * Generate a standard status report from structured data.
   */
  static generate(params: {
    agentId: AgentId;
    status: 'COMPLETE' | 'IN_PROGRESS' | 'BLOCKED' | 'ESCALATED';
    summary: string;
    metrics: Record<string, string | number>;
    nextAgent?: AgentId | 'RELEASE';
    warnings?: string[];
    details?: string;
  }): string {
    const agent = AGENT_ROSTER[params.agentId];
    const timestamp = new Date().toISOString();

    const metricsLines = Object.entries(params.metrics)
      .map(([key, value]) => `- **${key}:** ${value}`)
      .join('\n');

    const warningsBlock = params.warnings?.length
      ? `\n### ⚠️ Warnings\n${params.warnings.map(w => `- ${w}`).join('\n')}\n`
      : '';

    const detailsBlock = params.details
      ? `\n### Details\n${params.details}\n`
      : '';

    const nextLine = params.nextAgent
      ? `### Next: → ${params.nextAgent === 'RELEASE' ? '✅ RELEASE READY' : `${AGENT_ROSTER[params.nextAgent].emoji} ${params.nextAgent}`}`
      : '';

    return `## ${agent.emoji} ${agent.codename} Status Report
**Timestamp:** ${timestamp}
**Phase:** ${agent.phase.replace(/_/g, ' ')}
**Role:** ${agent.role}
**Status:** ${params.status}

### Summary
${params.summary}

### Key Metrics
${metricsLines}
${warningsBlock}${detailsBlock}
${nextLine}

---
*Generated by MAINFRAME orchestrator*
`;
  }

  /**
   * Generate a pipeline summary combining all agent reports.
   */
  static generatePipelineSummary(reports: Array<{
    agentId: AgentId;
    status: string;
    summary: string;
  }>): string {
    const timestamp = new Date().toISOString();

    const rows = reports.map(r => {
      const agent = AGENT_ROSTER[r.agentId];
      const statusEmoji = r.status === 'COMPLETE' ? '✅'
        : r.status === 'BLOCKED' ? '🚫'
        : r.status === 'IN_PROGRESS' ? '⏳'
        : '❓';
      return `| ${agent.emoji} ${agent.codename} | ${agent.role} | ${statusEmoji} ${r.status} | ${r.summary} |`;
    }).join('\n');

    return `# 🧠 MAINFRAME — Pipeline Summary
**Timestamp:** ${timestamp}

| Agent | Role | Status | Summary |
|-------|------|--------|---------|
${rows}

---
*Neon Arcade Game Studio — Powered by MAINFRAME*
`;
  }
}
