arrowParens: avoid
bracketSpacing: false
endOfLine: lf
htmlWhitespaceSensitivity: css
jsxSingleQuote: true
printWidth: 80
proseWrap: always
quoteProps: as-needed
semi: false
singleQuote: true
tabWidth: 2
trailingComma: es5
useTabs: false
