"use client";

import { useState } from "react";
import Nav from "../../components/Nav";
import Footer from "../../components/Footer";

const FILES = [
  { name: "model.py", active: true },
  { name: "api_wrapper.py", active: false },
  { name: "requirements.txt", active: false },
  { name: "README.md", active: false },
  { name: "config.yaml", active: false },
];

const FILE_CONTENTS: Record<string, string> = {
  "model.py": `import torch
import torch.nn as nn
import torch.nn.functional as F

class AttentionPooling(nn.Module):
    """
    Attention Pooling for Vision Transformers
    Auto-generated from: arxiv.org/abs/2401.08541

    This module implements learnable attention-based pooling
    as a replacement for standard [CLS] token pooling in ViTs.
    """

    def __init__(self, dim: int = 512, heads: int = 8, dropout: float = 0.1):
        super().__init__()
        self.heads = heads
        self.scale = (dim // heads) ** -0.5

        self.to_qkv = nn.Linear(dim, dim * 3, bias=False)
        self.attention = nn.MultiheadAttention(dim, heads, dropout=dropout)
        self.norm1 = nn.LayerNorm(dim)
        self.norm2 = nn.LayerNorm(dim)

        self.ffn = nn.Sequential(
            nn.Linear(dim, dim * 4),
            nn.GELU(),
            nn.Dropout(dropout),
            nn.Linear(dim * 4, dim),
            nn.Dropout(dropout),
        )

        self.pool_query = nn.Parameter(torch.randn(1, 1, dim))
        self.pool = nn.AdaptiveAvgPool1d(1)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        """
        Args:
            x: Input tensor of shape (batch, seq_len, dim)
        Returns:
            Pooled tensor of shape (batch, dim)
        """
        B, N, D = x.shape

        # Expand learnable query
        pool_query = self.pool_query.expand(B, -1, -1)

        # Cross-attention pooling
        attn_out, _ = self.attention(pool_query, x, x)
        x_pooled = self.norm1(pool_query + attn_out)

        # FFN
        x_pooled = self.norm2(x_pooled + self.ffn(x_pooled))

        return x_pooled.squeeze(1)


class AttentionPoolingViT(nn.Module):
    """Full ViT with Attention Pooling head."""

    def __init__(
        self,
        dim: int = 512,
        depth: int = 12,
        heads: int = 8,
        num_classes: int = 1000,
        patch_size: int = 16,
        image_size: int = 224,
    ):
        super().__init__()
        num_patches = (image_size // patch_size) ** 2
        patch_dim = 3 * patch_size * patch_size

        self.patch_embed = nn.Sequential(
            nn.Conv2d(3, dim, patch_size, stride=patch_size),
        )
        self.pos_embed = nn.Parameter(torch.randn(1, num_patches, dim))

        self.transformer = nn.TransformerEncoder(
            nn.TransformerEncoderLayer(
                d_model=dim, nhead=heads, dim_feedforward=dim * 4,
                dropout=0.1, activation="gelu", batch_first=True,
            ),
            num_layers=depth,
        )

        self.pool = AttentionPooling(dim=dim, heads=heads)
        self.head = nn.Linear(dim, num_classes)

    def forward(self, images: torch.Tensor) -> torch.Tensor:
        x = self.patch_embed(images).flatten(2).transpose(1, 2)
        x = x + self.pos_embed
        x = self.transformer(x)
        x = self.pool(x)
        return self.head(x)


if __name__ == "__main__":
    model = AttentionPoolingViT(dim=512, depth=12, heads=8, num_classes=1000)
    dummy = torch.randn(2, 3, 224, 224)
    out = model(dummy)
    print(f"Output shape: {out.shape}")  # (2, 1000)
    print(f"Parameters: {sum(p.numel() for p in model.parameters()):,}")`,

  "api_wrapper.py": `"""
StandardAPI Wrapper — Auto-generated by PaperCode
Provides a REST API interface for the AttentionPooling prototype.
"""

from fastapi import FastAPI, UploadFile, File
from pydantic import BaseModel
import torch
import io
from PIL import Image
from torchvision import transforms
from model import AttentionPoolingViT

app = FastAPI(title="AttentionPooling API", version="0.1.0")

# Load model
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = AttentionPoolingViT(dim=512, depth=12, heads=8, num_classes=1000)
model.to(device).eval()

transform = transforms.Compose([
    transforms.Resize(256),
    transforms.CenterCrop(224),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406],
                         std=[0.229, 0.224, 0.225]),
])

class PredictionResponse(BaseModel):
    class_id: int
    confidence: float
    logits_shape: list[int]

@app.get("/health")
def health():
    return {"status": "ok", "device": str(device)}

@app.post("/predict", response_model=PredictionResponse)
async def predict(file: UploadFile = File(...)):
    image_data = await file.read()
    image = Image.open(io.BytesIO(image_data)).convert("RGB")
    tensor = transform(image).unsqueeze(0).to(device)

    with torch.no_grad():
        logits = model(tensor)
        probs = torch.softmax(logits, dim=-1)
        class_id = probs.argmax(dim=-1).item()
        confidence = probs.max().item()

    return PredictionResponse(
        class_id=class_id,
        confidence=round(confidence, 4),
        logits_shape=list(logits.shape),
    )

@app.get("/model/info")
def model_info():
    return {
        "architecture": "AttentionPoolingViT",
        "parameters": sum(p.numel() for p in model.parameters()),
        "source_paper": "arxiv.org/abs/2401.08541",
        "generated_by": "PaperCode v0.1",
    }`,

  "requirements.txt": `torch>=2.1.0
torchvision>=0.16.0
fastapi>=0.104.0
uvicorn>=0.24.0
pillow>=10.0.0
pydantic>=2.5.0`,

  "README.md": `# Attention Pooling for Vision Transformers

> Auto-generated prototype by PaperCode
> Source: arxiv.org/abs/2401.08541

## Quick Start

\`\`\`bash
pip install -r requirements.txt
python model.py           # Test model forward pass
uvicorn api_wrapper:app   # Start API server
\`\`\`

## API Endpoints

- \`GET  /health\`      — Health check
- \`POST /predict\`     — Image classification
- \`GET  /model/info\`  — Model metadata

## Architecture

AttentionPooling replaces standard CLS token pooling with a
learnable cross-attention mechanism, improving classification
accuracy by ~1.2% on ImageNet-1K.`,

  "config.yaml": `# PaperCode Generation Config
source:
  type: arxiv
  url: "https://arxiv.org/abs/2401.08541"
  title: "Attention Pooling for Vision Transformers"

model:
  architecture: AttentionPoolingViT
  dim: 512
  depth: 12
  heads: 8
  num_classes: 1000
  image_size: 224
  patch_size: 16

training:
  batch_size: 32
  learning_rate: 0.0003
  weight_decay: 0.05
  epochs: 300
  warmup_epochs: 10

api:
  port: 8000
  workers: 1`,
};

const API_TEST_RESPONSE = `{
  "status": "ok",
  "device": "cuda",
  "response_time_ms": 12
}`;

export default function Viewer() {
  const [activeFile, setActiveFile] = useState("model.py");
  const [apiTab, setApiTab] = useState<"code" | "test">("code");
  const [testResult, setTestResult] = useState("");
  const [testing, setTesting] = useState(false);

  const runTest = () => {
    setTesting(true);
    setTestResult("");
    setTimeout(() => {
      setTestResult(API_TEST_RESPONSE);
      setTesting(false);
    }, 1200);
  };

  return (
    <div className="min-h-screen flex flex-col">
      <Nav />

      <div className="max-w-6xl mx-auto px-4 py-8 w-full flex-1">
        {/* Header */}
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 mb-6">
          <div>
            <h1 className="text-xl font-bold text-white">
              Attention Pooling for Vision Transformers
            </h1>
            <p className="text-gray-500 text-sm mt-1">
              arxiv.org/abs/2401.08541 — Generated in 47s — 156 lines
            </p>
          </div>
          <div className="flex gap-2">
            <button className="bg-gray-800 border border-gray-700 text-gray-300 px-4 py-2 rounded-lg text-sm hover:border-green-500/50 transition-colors">
              Copy All
            </button>
            <button className="bg-green-500 text-gray-950 px-4 py-2 rounded-lg text-sm font-medium hover:bg-green-400 transition-colors">
              Download .zip
            </button>
          </div>
        </div>

        <div className="flex flex-col lg:flex-row gap-4">
          {/* File tree */}
          <div className="lg:w-48 shrink-0">
            <div className="bg-gray-900 border border-gray-800 rounded-lg overflow-hidden">
              <div className="px-3 py-2 text-xs text-gray-500 uppercase tracking-wider border-b border-gray-800">
                Files
              </div>
              {FILES.map((f) => (
                <button
                  key={f.name}
                  onClick={() => setActiveFile(f.name)}
                  className={`w-full text-left px-3 py-2 text-sm transition-colors ${
                    activeFile === f.name
                      ? "bg-gray-800 text-green-400"
                      : "text-gray-400 hover:bg-gray-800/50 hover:text-gray-300"
                  }`}
                >
                  {f.name}
                </button>
              ))}
            </div>

            {/* Validation status */}
            <div className="bg-gray-900 border border-gray-800 rounded-lg p-3 mt-4">
              <div className="text-xs text-gray-500 uppercase tracking-wider mb-3">Checks</div>
              {[
                { label: "Syntax", pass: true },
                { label: "Imports", pass: true },
                { label: "Type hints", pass: true },
                { label: "Forward pass", pass: true },
                { label: "API routes", pass: true },
              ].map((c) => (
                <div key={c.label} className="flex items-center gap-2 text-xs py-1">
                  <span className={c.pass ? "text-green-400" : "text-red-400"}>
                    {c.pass ? "✓" : "✗"}
                  </span>
                  <span className="text-gray-400">{c.label}</span>
                </div>
              ))}
            </div>
          </div>

          {/* Code viewer */}
          <div className="flex-1 min-w-0">
            <div className="bg-gray-900 border border-gray-800 rounded-lg overflow-hidden">
              <div className="flex items-center justify-between px-4 py-2.5 border-b border-gray-800">
                <div className="flex items-center gap-2">
                  <div className="w-3 h-3 rounded-full bg-red-500/70" />
                  <div className="w-3 h-3 rounded-full bg-yellow-500/70" />
                  <div className="w-3 h-3 rounded-full bg-green-500/70" />
                  <span className="ml-3 text-xs text-gray-500">{activeFile}</span>
                </div>
                <div className="flex gap-1">
                  <button
                    onClick={() => setApiTab("code")}
                    className={`px-3 py-1 text-xs rounded ${
                      apiTab === "code"
                        ? "bg-gray-700 text-white"
                        : "text-gray-500 hover:text-gray-300"
                    }`}
                  >
                    Code
                  </button>
                  <button
                    onClick={() => setApiTab("test")}
                    className={`px-3 py-1 text-xs rounded ${
                      apiTab === "test"
                        ? "bg-gray-700 text-white"
                        : "text-gray-500 hover:text-gray-300"
                    }`}
                  >
                    API Test
                  </button>
                </div>
              </div>

              {apiTab === "code" ? (
                <pre className="p-4 text-sm overflow-x-auto text-gray-300 leading-relaxed max-h-[600px] overflow-y-auto">
                  <code>{FILE_CONTENTS[activeFile]}</code>
                </pre>
              ) : (
                <div className="p-4">
                  <div className="mb-4">
                    <div className="text-xs text-gray-500 mb-2">
                      GET /health
                    </div>
                    <button
                      onClick={runTest}
                      disabled={testing}
                      className="bg-green-500 text-gray-950 px-4 py-1.5 rounded text-sm font-medium hover:bg-green-400 transition-colors disabled:opacity-50"
                    >
                      {testing ? "Testing..." : "Send Request"}
                    </button>
                  </div>
                  {testResult && (
                    <div>
                      <div className="text-xs text-gray-500 mb-2">Response:</div>
                      <pre className="bg-gray-800 rounded p-3 text-sm text-green-400 overflow-x-auto">
                        {testResult}
                      </pre>
                    </div>
                  )}
                </div>
              )}
            </div>
          </div>
        </div>
      </div>

      <Footer />
    </div>
  );
}
