#!/usr/bin/env python3
"""
Generate a new crucible-style agent from a task description.
Creates the full skill folder structure with SKILL.md, scripts/, references/, assets/ and blueprint.json.
"""

import json
import os
import sys
import re
import argparse
from datetime import datetime, timezone
from pathlib import Path


SKILL_MD_TEMPLATE = """---
name: {name}
description: >
  {description}
license: 'MIT (see repo LICENSE)'
triggers:
{triggers}
---

# {title}

{overview}

## Capabilities

{capabilities}

## I/O Contract

### Inputs
{inputs}

### Outputs
{outputs}

## Usage

```bash
# Run the agent
python scripts/run_agent.py --config assets/blueprint.json
```

## Scripts

- `scripts/run_agent.py` — Main agent execution loop
- `scripts/validate_agent.py` — Self-test and health check

## References

- [`references/architecture.md`](references/architecture.md) — Design documentation
- [`references/capability-map.md`](references/capability-map.md) — Detailed capability inventory
- [`references/evolution-log.md`](references/evolution-log.md) — Improvement history

## Evolution

This agent tracks its own performance. After each run:
1. Logs execution metrics to `evolution-log.md`
2. Updates utility score in `blueprint.json`
3. Flags failure patterns for `skill-improver` review
"""

BLUEPRINT_TEMPLATE = {
    "schema_version": 2,
    "agent": {
        "name": "",
        "type": "workflow",
        "stage": "workflow",
        "description": "",
        "triggers": [],
        "capabilities": [],
        "composed_from": [],
        "new_components": [],
        "io_contract": {
            "inputs": [],
            "outputs": []
        },
        "resource_requirements": {
            "memory": "medium",
            "compute": "medium",
            "api_keys": []
        },
        "evolution": {
            "utility_score": 0,
            "runs": 0,
            "successes": 0,
            "failures": 0,
            "last_improved": None,
            "failure_patterns": [],
            "created_at": "",
            "created_by": "agent-designer"
        }
    }
}

RUN_AGENT_TEMPLATE = '''#!/usr/bin/env python3
"""
Main execution loop for {name} agent.
Auto-generated by agent-designer.
"""

import json
import sys
import os
import logging
from datetime import datetime, timezone
from pathlib import Path

logging.basicConfig(level=logging.INFO, format='%(asctime)s [%(levelname)s] %(message)s')
logger = logging.getLogger('{name}')


def load_blueprint(blueprint_path: str) -> dict:
    """Load the agent blueprint."""
    with open(blueprint_path, 'r') as f:
        return json.load(f)


def update_evolution(blueprint_path: str, success: bool, error: str = None):
    """Update evolution metrics after a run."""
    blueprint = load_blueprint(blueprint_path)
    evo = blueprint['agent']['evolution']
    
    evo['runs'] += 1
    if success:
        evo['successes'] += 1
        # Increase utility score (capped at 100)
        evo['utility_score'] = min(100, evo['utility_score'] + 1)
    else:
        evo['failures'] += 1
        # Decrease utility score (min 0)
        evo['utility_score'] = max(0, evo['utility_score'] - 2)
        if error:
            evo['failure_patterns'].append({{
                'timestamp': datetime.now(timezone.utc).isoformat(),
                'error': error[:200],
            }})
            # Keep only last 20 failure patterns
            evo['failure_patterns'] = evo['failure_patterns'][-20:]
    
    evo['last_improved'] = datetime.now(timezone.utc).isoformat()
    
    with open(blueprint_path, 'w') as f:
        json.dump(blueprint, f, indent=2)
    
    logger.info(f"Evolution updated: score={{evo['utility_score']}}, "
                f"runs={{evo['runs']}}, success_rate={{evo['successes']/max(evo['runs'],1):.0%}}")


def run(config_path: str = None):
    """Main agent execution."""
    script_dir = Path(__file__).parent.parent
    blueprint_path = script_dir / 'assets' / 'blueprint.json'
    
    if config_path:
        blueprint_path = Path(config_path)
    
    blueprint = load_blueprint(str(blueprint_path))
    agent = blueprint['agent']
    
    logger.info(f"Starting agent: {{agent['name']}}")
    logger.info(f"Capabilities: {{', '.join(agent['capabilities'])}}")
    logger.info(f"Utility score: {{agent['evolution']['utility_score']}}")
    
    try:
        # === AGENT LOGIC HERE ===
        # This is the main execution point.
        # Implement your agent's core logic below.
        
        logger.info("Agent execution complete.")
        update_evolution(str(blueprint_path), success=True)
        
    except Exception as e:
        logger.error(f"Agent execution failed: {{e}}")
        update_evolution(str(blueprint_path), success=False, error=str(e))
        raise


if __name__ == '__main__':
    import argparse
    parser = argparse.ArgumentParser(description='Run {name} agent')
    parser.add_argument('--config', help='Path to blueprint.json')
    args = parser.parse_args()
    run(args.config)
'''

VALIDATE_AGENT_TEMPLATE = '''#!/usr/bin/env python3
"""
Validate {name} agent configuration and health.
Auto-generated by agent-designer.
"""

import json
import sys
from pathlib import Path


def validate(agent_dir: str = None):
    """Validate agent configuration."""
    if agent_dir is None:
        agent_dir = Path(__file__).parent.parent
    else:
        agent_dir = Path(agent_dir)
    
    errors = []
    warnings = []
    
    # Check SKILL.md exists
    skill_md = agent_dir / 'SKILL.md'
    if not skill_md.exists():
        errors.append("Missing SKILL.md")
    
    # Check blueprint.json
    blueprint_path = agent_dir / 'assets' / 'blueprint.json'
    if not blueprint_path.exists():
        errors.append("Missing assets/blueprint.json")
    else:
        with open(blueprint_path) as f:
            blueprint = json.load(f)
        
        agent = blueprint.get('agent', {{}})
        
        if not agent.get('name'):
            errors.append("blueprint.json: missing agent.name")
        if not agent.get('description'):
            warnings.append("blueprint.json: missing agent.description")
        if not agent.get('triggers'):
            warnings.append("blueprint.json: no triggers defined")
        if not agent.get('capabilities'):
            warnings.append("blueprint.json: no capabilities listed")
    
    # Check required directories
    for subdir in ['scripts', 'references']:
        if not (agent_dir / subdir).exists():
            warnings.append(f"Missing {{subdir}}/ directory")
    
    # Report
    print(f"\\n🔍 Validation: {{agent_dir.name}}")
    print("=" * 50)
    
    if errors:
        print("\\n❌ ERRORS:")
        for e in errors:
            print(f"  • {{e}}")
    
    if warnings:
        print("\\n⚠️  WARNINGS:")
        for w in warnings:
            print(f"  • {{w}}")
    
    if not errors and not warnings:
        print("\\n✅ All checks passed!")
    
    return len(errors) == 0


if __name__ == '__main__':
    agent_dir = sys.argv[1] if len(sys.argv) > 1 else None
    ok = validate(agent_dir)
    sys.exit(0 if ok else 1)
'''


def slugify(text: str) -> str:
    """Convert text to a slug."""
    text = text.lower().strip()
    text = re.sub(r'[^\w\s-]', '', text)
    text = re.sub(r'[\s_]+', '-', text)
    text = re.sub(r'-+', '-', text)
    return text[:50].strip('-')


def generate_agent(task: str, output_dir: str, agent_type: str = 'workflow'):
    """Generate a new agent skill from a task description."""
    
    # Derive name from task
    name = slugify(task)
    if not name.startswith(('agent-', 'tool-', 'workflow-', 'review-')):
        name = f"agent-{name}"
    
    title = task.title()
    agent_dir = Path(output_dir) / name
    
    # Create directory structure
    for subdir in ['scripts', 'references', 'assets']:
        (agent_dir / subdir).mkdir(parents=True, exist_ok=True)
    
    # Generate triggers
    words = task.lower().split()
    triggers = [f"  - '{task.lower()}'"]
    if len(words) > 2:
        triggers.append(f"  - '{' '.join(words[:3])}'")
    triggers.append(f"  - '{name}'")
    
    # Generate capabilities
    capabilities_list = [w for w in words if len(w) > 3 and w not in 
                         ('the', 'that', 'this', 'with', 'from', 'should', 'would', 'could')]
    
    # Write SKILL.md
    skill_md = SKILL_MD_TEMPLATE.format(
        name=name,
        title=title,
        description=task,
        triggers='\n'.join(triggers),
        overview=f"An auto-generated agent designed to: {task}",
        capabilities='\n'.join(f"- **{cap}**: Core capability" for cap in capabilities_list[:5]),
        inputs="- Task configuration (JSON)\n- Context parameters",
        outputs="- Execution report (Markdown)\n- Metrics (JSON)",
    )
    (agent_dir / 'SKILL.md').write_text(skill_md)
    
    # Write blueprint.json
    blueprint = json.loads(json.dumps(BLUEPRINT_TEMPLATE))
    blueprint['agent']['name'] = name
    blueprint['agent']['type'] = agent_type
    blueprint['agent']['stage'] = agent_type
    blueprint['agent']['description'] = task
    blueprint['agent']['triggers'] = [t.strip().strip("- '\"") for t in triggers]
    blueprint['agent']['capabilities'] = capabilities_list[:5]
    blueprint['agent']['evolution']['created_at'] = datetime.now(timezone.utc).isoformat()
    
    (agent_dir / 'assets' / 'blueprint.json').write_text(json.dumps(blueprint, indent=2))
    
    # Write run_agent.py
    (agent_dir / 'scripts' / 'run_agent.py').write_text(RUN_AGENT_TEMPLATE.format(name=name))
    
    # Write validate_agent.py
    (agent_dir / 'scripts' / 'validate_agent.py').write_text(VALIDATE_AGENT_TEMPLATE.format(name=name))
    
    # Write architecture.md
    arch_content = f"""# {title} — Architecture

## Overview
{task}

## Component Diagram

```
┌─────────────────────┐
│   {name}             │
├─────────────────────┤
│ scripts/run_agent.py │ ← Main execution loop
│ assets/blueprint.json│ ← Config + evolution state
│ SKILL.md             │ ← Routing + triggers
└─────────────────────┘
```

## Evolution Strategy

This agent uses Crucible's adaptive utility score system:
- +1 on successful execution
- -2 on failure (to create improvement pressure)
- Failure patterns logged for `skill-improver` analysis
- Periodic review via `agent-reflector`

## Created

- **Date**: {datetime.now(timezone.utc).strftime('%Y-%m-%d')}
- **By**: agent-designer
- **Method**: Auto-generated from task description
"""
    (agent_dir / 'references' / 'architecture.md').write_text(arch_content)
    
    # Write evolution-log.md
    evo_content = f"""# Evolution Log — {name}

## Initial Creation
- **Date**: {datetime.now(timezone.utc).strftime('%Y-%m-%d')}
- **Utility Score**: 0
- **Status**: New agent, no runs yet

---

## Run History

| Date | Success | Score | Notes |
|------|---------|-------|-------|
| — | — | 0 | Initial creation |
"""
    (agent_dir / 'references' / 'evolution-log.md').write_text(evo_content)
    
    # Write capability-map.md
    cap_content = f"""# Capability Map — {name}

## Core Capabilities

{chr(10).join(f'### {cap.title()}' + chr(10) + f'- Status: 🟡 Planned' + chr(10) + f'- Dependencies: None' + chr(10) for cap in capabilities_list[:5])}

## Integration Points

- Composed from: (none yet — fill in during implementation)
- Used by: (none yet — will be discovered)
"""
    (agent_dir / 'references' / 'capability-map.md').write_text(cap_content)
    
    print(f"\n✅ Agent generated: {agent_dir}")
    print(f"   📄 SKILL.md")
    print(f"   📦 assets/blueprint.json")
    print(f"   🔧 scripts/run_agent.py")
    print(f"   🔧 scripts/validate_agent.py")
    print(f"   📚 references/architecture.md")
    print(f"   📚 references/evolution-log.md")
    print(f"   📚 references/capability-map.md")
    
    return str(agent_dir)


def main():
    parser = argparse.ArgumentParser(description='Generate a new agent from task description')
    parser.add_argument('--task', required=True, help='Task description for the agent')
    parser.add_argument('--output', default='skills/', help='Output directory (default: skills/)')
    parser.add_argument('--type', default='workflow', choices=['workflow', 'tool', 'review', 'meta', 'service'],
                        help='Agent type')
    
    args = parser.parse_args()
    generate_agent(args.task, args.output, args.type)


if __name__ == '__main__':
    main()
