import fs from 'fs';
import path from 'path';
import { loadMemory, saveMemory, syncScriptsToMemory, syncAgentsToMemory, routeToSkill } from './skill-memory.mjs';

/**
 * 🏗️ AGENT SPAWNER — Create new agents from task descriptions
 * 
 * Integrates with the existing scripts/agents/ registry system.
 * Uses Crucible's "Let Agents Design Agents" approach.
 * 
 * This script:
 * 1. Analyzes a task description
 * 2. Checks skill memory for existing matches
 * 3. If no match → spawns a new agent definition + skeleton script
 * 4. Registers in both agents/registry.json and skill-memory
 */

const AGENTS_DIR = path.join(process.cwd(), 'scripts', 'agents');
const SCRIPTS_DIR = path.join(process.cwd(), 'scripts');
const STATES_DIR = path.join(process.cwd(), 'scripts', 'agent-states');
const SKILLS_DIR = path.join(process.cwd(), 'skills');

// ── Agent Templates ─────────────────────────────────────────────────────────

const AGENT_TYPES = {
  'content-producer': {
    capabilities: ['content-generation', 'asset-creation', 'quality-check'],
    template: 'empire-cycle',
    scripts: ['producer', 'validator'],
  },
  'platform-publisher': {
    capabilities: ['api-upload', 'metadata-optimization', 'quota-management'],
    template: 'uploader',
    scripts: ['uploader', 'verifier'],
  },
  'intel-collector': {
    capabilities: ['data-fetching', 'analysis', 'reporting'],
    template: 'intel-fetcher',
    scripts: ['fetcher', 'analyzer'],
  },
  'engagement-agent': {
    capabilities: ['community-interaction', 'response-generation', 'sentiment-analysis'],
    template: 'engagement',
    scripts: ['engager', 'monitor'],
  },
  'optimizer': {
    capabilities: ['performance-analysis', 'a-b-testing', 'recommendation'],
    template: 'optimizer',
    scripts: ['analyzer', 'optimizer'],
  },
  'monitor': {
    capabilities: ['health-check', 'alerting', 'reporting'],
    template: 'monitor',
    scripts: ['monitor', 'reporter'],
  },
};

// ── Task Analysis ───────────────────────────────────────────────────────────

function analyzeTask(description) {
  const desc = description.toLowerCase();
  
  // Detect platform
  let platform = 'general';
  if (desc.includes('youtube') || desc.includes('yt')) platform = 'youtube';
  else if (desc.includes('instagram') || desc.includes('ig') || desc.includes('reels')) platform = 'instagram';
  else if (desc.includes('facebook') || desc.includes('fb')) platform = 'facebook';
  else if (desc.includes('twitter') || desc.includes('x.com') || desc.includes('threads')) platform = 'twitter';
  else if (desc.includes('moltbook')) platform = 'moltbook';
  else if (desc.includes('tiktok')) platform = 'tiktok';
  
  // Detect agent type
  let type = 'content-producer';
  if (desc.includes('upload') || desc.includes('publish') || desc.includes('post')) type = 'platform-publisher';
  else if (desc.includes('intel') || desc.includes('fetch') || desc.includes('scrape') || desc.includes('collect')) type = 'intel-collector';
  else if (desc.includes('engage') || desc.includes('reply') || desc.includes('comment')) type = 'engagement-agent';
  else if (desc.includes('optimi') || desc.includes('improve') || desc.includes('enhance')) type = 'optimizer';
  else if (desc.includes('monitor') || desc.includes('watch') || desc.includes('alert')) type = 'monitor';
  
  // Extract key topics
  const stopWords = new Set(['the', 'a', 'an', 'is', 'are', 'that', 'this', 'for', 'and', 'or', 'to', 'in', 'on', 'at', 'by', 'with', 'from', 'of', 'do', 'new', 'create', 'make', 'build', 'agent']);
  const topics = desc.split(/\s+/)
    .map(w => w.replace(/[^a-z0-9]/g, ''))
    .filter(w => w.length > 2 && !stopWords.has(w))
    .slice(0, 5);
  
  return { platform, type, topics, description };
}

// ── Agent Skeleton Script Generator ─────────────────────────────────────────

function generateScript(agentName, analysis) {
  const { platform, type, topics } = analysis;
  const typeConfig = AGENT_TYPES[type] || AGENT_TYPES['content-producer'];
  
  return `import fs from 'fs';
import path from 'path';
import { executeWithEvolution } from './agent-evolution-loop.mjs';
import { recordResult } from './skill-memory.mjs';

/**
 * 🤖 ${agentName} — Auto-generated Agent
 * 
 * Platform: ${platform}
 * Type: ${type}
 * Capabilities: ${typeConfig.capabilities.join(', ')}
 * Topics: ${topics.join(', ')}
 * 
 * Generated by agent-spawner.mjs
 * Uses Crucible's evolution tracking.
 */

const STATE_FILE = path.join(process.cwd(), 'scripts', 'agent-states', '${agentName}-state.json');

function loadState() {
  if (fs.existsSync(STATE_FILE)) {
    try { return JSON.parse(fs.readFileSync(STATE_FILE, 'utf8')); } catch {}
  }
  return { 
    lastRun: null, 
    totalRuns: 0, 
    totalSuccesses: 0,
    history: [] 
  };
}

function saveState(state) {
  state.lastRun = new Date().toISOString();
  state.totalRuns++;
  fs.writeFileSync(STATE_FILE, JSON.stringify(state, null, 2));
}

async function main() {
  console.log('\\n🤖 ${agentName} starting...');
  
  const result = await executeWithEvolution('${agentName}', async () => {
    const state = loadState();
    
    // ══════════════════════════════════════════════════════════════
    // TODO: Implement ${type} logic for ${platform}
    // 
    // Available capabilities: ${typeConfig.capabilities.join(', ')}
    // 
    // Template pattern: ${typeConfig.template}
    // ══════════════════════════════════════════════════════════════
    
    console.log('  📋 Task: ${analysis.description}');
    console.log('  🎯 Platform: ${platform}');
    console.log('  📊 Run #' + (state.totalRuns + 1));
    
    // Your implementation goes here
    // ...
    
    state.totalSuccesses++;
    state.history.push({
      date: new Date().toISOString(),
      result: 'success',
    });
    saveState(state);
    
    return { status: 'completed', runs: state.totalRuns };
  }, { platform: '${platform}', type: '${type}' });
  
  if (result.success) {
    console.log('✅ ${agentName} completed successfully');
  } else {
    console.error('❌ ${agentName} failed:', result.error?.message);
  }
}

main().catch(console.error);
`;
}

// ── Spawn Agent ──────────────────────────────────────────────────────────────

export function spawnAgent(taskDescription) {
  const analysis = analyzeTask(taskDescription);
  
  // Check for existing matches first
  const memory = loadMemory();
  const existing = routeToSkill(taskDescription, memory);
  
  if (existing.length > 0 && existing[0].score > 30) {
    console.log(`\n🔍 Found existing skill match: ${existing[0].name} (score: ${existing[0].score.toFixed(1)})`);
    console.log(`   Utility: ${existing[0].skill.utilityScore}/100`);
    console.log(`   Consider using this instead of creating a new agent.`);
    console.log(`   To force creation, add --force flag.\n`);
    
    if (!process.argv.includes('--force')) {
      return null;
    }
  }
  
  // Generate agent name
  const slug = analysis.topics.slice(0, 3).join('-');
  const agentName = `${analysis.platform}-${slug}`;
  
  console.log(`\n🏗️ Spawning new agent: ${agentName}`);
  console.log(`   Platform: ${analysis.platform}`);
  console.log(`   Type: ${analysis.type}`);
  console.log(`   Topics: ${analysis.topics.join(', ')}`);
  
  // 1. Create agent definition JSON
  const agentDef = {
    agent_name: agentName,
    description: taskDescription,
    platform: analysis.platform,
    type: analysis.type,
    capabilities: AGENT_TYPES[analysis.type]?.capabilities || [],
    topics: analysis.topics,
    created_at: new Date().toISOString(),
    created_by: 'agent-spawner',
    status: 'active',
    evolution: {
      utility_score: 50,
      runs: 0,
      created_method: 'crucible-spawn',
    },
  };
  
  const agentFile = path.join(AGENTS_DIR, `${agentName}.json`);
  fs.mkdirSync(AGENTS_DIR, { recursive: true });
  fs.writeFileSync(agentFile, JSON.stringify(agentDef, null, 2));
  console.log(`   📄 Agent definition: scripts/agents/${agentName}.json`);
  
  // 2. Create skeleton script
  const scriptContent = generateScript(agentName, analysis);
  const scriptFile = path.join(SCRIPTS_DIR, `${agentName}.mjs`);
  fs.writeFileSync(scriptFile, scriptContent);
  console.log(`   🔧 Agent script: scripts/${agentName}.mjs`);
  
  // 3. Create initial state
  fs.mkdirSync(STATES_DIR, { recursive: true });
  const stateFile = path.join(STATES_DIR, `${agentName}-state.json`);
  fs.writeFileSync(stateFile, JSON.stringify({
    lastRun: null,
    totalRuns: 0,
    totalSuccesses: 0,
    history: [],
  }, null, 2));
  console.log(`   📊 Agent state: scripts/agent-states/${agentName}-state.json`);
  
  // 4. Register in skill memory
  if (!memory.skills[agentName]) {
    memory.skills[agentName] = {
      name: agentName,
      type: analysis.type,
      utilityScore: 50,
      runs: 0,
      successes: 0,
      failures: 0,
      avgDurationMs: 0,
      lastUsed: null,
      lastSuccess: null,
      lastFailure: null,
      failurePatterns: [],
      evolutionHistory: [{
        timestamp: new Date().toISOString(),
        type: 'creation',
        description: `Spawned from task: ${taskDescription}`,
        trigger: 'agent-spawner',
      }],
      composedFrom: [],
      usedBy: [],
      tags: analysis.topics,
      source: `scripts/${agentName}.mjs`,
    };
  }
  
  if (!memory.agents[agentName]) {
    memory.agents[agentName] = {
      name: agentName,
      description: taskDescription,
      topics: analysis.topics,
      platform: analysis.platform,
      registeredAt: new Date().toISOString(),
      utilityScore: 50,
      runs: 0,
    };
  }
  
  saveMemory(memory);
  console.log(`   🧠 Registered in skill memory`);
  
  // 5. Create SKILL.md in skills/ if it doesn't exist
  const skillDir = path.join(SKILLS_DIR, agentName);
  if (!fs.existsSync(skillDir)) {
    fs.mkdirSync(skillDir, { recursive: true });
    const skillMd = `---
name: ${agentName}
description: >
  ${taskDescription}
triggers:
  - '${agentName}'
  - '${analysis.topics.join("' \n  - '")}'
---

# ${agentName}

Auto-generated agent for: ${taskDescription}

## Type: ${analysis.type}
## Platform: ${analysis.platform}

## Capabilities
${(AGENT_TYPES[analysis.type]?.capabilities || []).map(c => `- ${c}`).join('\n')}

## Execution

\`\`\`bash
node scripts/${agentName}.mjs
\`\`\`

## Evolution

This agent uses Crucible's adaptive evolution tracking.
- Utility score starts at 50/100
- Success: +2, Failure: -5
- Automatic reflection on failure patterns
`;
    fs.writeFileSync(path.join(skillDir, 'SKILL.md'), skillMd);
    console.log(`   📚 Skill definition: skills/${agentName}/SKILL.md`);
  }
  
  console.log(`\n✅ Agent ${agentName} spawned successfully!`);
  console.log(`   Run it: node scripts/${agentName}.mjs`);
  
  return agentName;
}

// ── List spawned agents ──────────────────────────────────────────────────────

function listSpawnedAgents() {
  const memory = loadMemory();
  const spawned = Object.values(memory.agents).filter(a => a.platform);
  
  if (spawned.length === 0) {
    console.log('No spawned agents yet. Use: node scripts/agent-spawner.mjs spawn "task description"');
    return;
  }
  
  console.log(`\n🤖 Spawned Agents (${spawned.length}):\n`);
  for (const agent of spawned) {
    const skill = memory.skills[agent.name];
    const score = skill?.utilityScore ?? 'N/A';
    const runs = skill?.runs ?? 0;
    console.log(`  ${agent.name}`);
    console.log(`    Platform: ${agent.platform} | Score: ${score}/100 | Runs: ${runs}`);
    console.log(`    ${agent.description?.slice(0, 80)}`);
    console.log();
  }
}

// ── CLI ──────────────────────────────────────────────────────────────────────

const command = process.argv[2];

if (command === 'spawn') {
  const taskDesc = process.argv.slice(3).join(' ');
  if (!taskDesc) {
    console.error('Usage: node scripts/agent-spawner.mjs spawn "task description"');
    console.error('Example: node scripts/agent-spawner.mjs spawn "monitor youtube shorts performance"');
    process.exit(1);
  }
  spawnAgent(taskDesc);
  
} else if (command === 'list') {
  listSpawnedAgents();
  
} else if (command === 'analyze') {
  const taskDesc = process.argv.slice(3).join(' ');
  if (!taskDesc) {
    console.error('Usage: node scripts/agent-spawner.mjs analyze "task description"');
    process.exit(1);
  }
  const analysis = analyzeTask(taskDesc);
  console.log('\n🔍 Task Analysis:', JSON.stringify(analysis, null, 2));
  
  const matches = routeToSkill(taskDesc);
  if (matches.length > 0) {
    console.log('\n🧭 Existing skill matches:');
    matches.forEach((m, i) => console.log(`  ${i + 1}. ${m.name} (score: ${m.score.toFixed(1)})`));
  } else {
    console.log('\n🆕 No existing matches — a new agent would be created.');
  }
  
} else {
  console.log(`
🏗️ Agent Spawner — Let Agents Design Agents

Commands:
  spawn     Create a new agent from task description
  list      List all spawned agents
  analyze   Analyze a task without creating

Usage:
  node scripts/agent-spawner.mjs spawn "monitor youtube shorts performance and suggest improvements"
  node scripts/agent-spawner.mjs spawn "collect trending topics from instagram explore page"
  node scripts/agent-spawner.mjs spawn "optimize moltbook post engagement timing"
  node scripts/agent-spawner.mjs list
  node scripts/agent-spawner.mjs analyze "generate faceless youtube videos about AI news"
  `);
}
